defaults: &defaults
  working_directory: ~/code
  docker:
    - image: circleci/android:api-27-alpha
  environment:
    TZ: Europe/Madrid
    JVM_OPTS: -Xmx3200m
    GRADLE_OPTS: '-Dorg.gradle.daemon=false'
    _JAVA_OPTIONS: "-Xms256m -Xmx1280m -XX:MaxPermSize=350m"

configure_gradle: &configure_gradle
  name: Configure Gradle Properties
  command: |
    mkdir -p ~/.gradle
    touch ~/.gradle/gradle.properties
    echo "org.gradle.daemon=false" > ~/.gradle/gradle.properties
    echo "org.gradle.jvmargs=-Xmx1536m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError" >> ~/.gradle/gradle.properties
    echo "apiKey=put_y0ur_pubg_api_k3y_here" > pubg-api.properties

download_gradle_dependencies: &download_gradle_dependencies
  name: Download dependencies
  command: ./gradlew dependencies


version: 2
jobs:
  tests:
    <<: *defaults
    steps:
      - checkout
      - run: *configure_gradle
      - restore_cache:
          key: jars--{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run: *download_gradle_dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars--{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew test --stacktrace -PdisablePreDex
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results

  ktlint:
    <<: *defaults
    steps:
      - checkout
      - run: *configure_gradle
      - restore_cache:
          key: jars--{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run: *download_gradle_dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars--{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run ktlint
          command: ./gradlew ktlint --stacktrace -PdisablePreDex
      - store_artifacts:
          path: app/build/reports
          destination: reports

workflows:
  version: 2
  test_and_ktlint:
    jobs:
      - tests
      - ktlint